# Generated by Django 5.1.6 on 2025-02-18 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Անուն')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Էլ․ հասցե։')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Բաժանորդ',
                'verbose_name_plural': 'Բաժանորդներ',
            },
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars_qty',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopapi.product', verbose_name='Ապրանքի Նկարներ։'),
        ),
    ]
